version: "2"
services:
  api:
    build:
      context: ./api
    restart: always
    working_dir: /var/www
    volumes:
      - ./api:/var/www
    links:
      - mongo
    # enviroments:
  # The Web Server
  nginx:
    build:
      context: ./
      dockerfile: nginx.dockerfile
    working_dir: /var/www
    volumes_from:
      - api
    ports:
      - 8080:80
        # The Database
  mongo:
    container_name: mongo
    image: mongo:3.6.5-jessie
    volumes:
      - /data/blog:/data/db
    ports:
        - "28000:27017"
