version: "2"
services:
  api:
    build:
      context: ./api
    working_dir: /var/www
    volumes:
      - ./api:/var/www
  nginx:
    build:
      context: ./
      dockerfile: nginx.dockerfile
    working_dir: /var/www
    volumes_from:
      - api
    ports:
      - 8080:80
  mongo:
    image: mongo:3.6.5-jessie
    volumes:
      - ~/.mongo/blog:/data/db
    ports:
        - "28000:27017"
